---
- hosts: all
  gather_facts: yes

  tasks:
    - name: Add Ansible inventory mappings to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {% for host in groups['all'] %}
          {{ hostvars[host].ansible_host }} {{ host }}
          {% endfor %}

    - name: Set hostnames
      hostname:
        name: "{{ inventory_hostname }}"