---
- hosts: all
  gather_facts: yes
  vars_files:
    - env_variables

  tasks:
    - name: Update /etc/hosts file
      copy:
        content: "{{ hosts_file }}"
        dest: /etc/hosts

- hosts: master
  tasks:
    - name: Update master hostname
      shell: echo "master" > /etc/hostname

- hosts: workers
  tasks:
    - name: Update worker01 hostname
      shell: echo "worker01" > /etc/hostname