---
- hosts: master
  vars_files:
    - ../env_variables

  tasks:
    - name: Add Docker apt-key to repository
      apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      tags:
        - repository

    - name: Add Kubernetes apt-key to repository on Ubuntu
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      tags:
        - repository

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: 'docker'
      tags:
        - repository

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'
      tags:
        - repository

    - name: Install required packages
      apt:
       name: "{{ ubuntu_packages }}"
       state: latest
       update_cache: yes

    - name: Install system updates
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Set firewall rules
      shell: |
        firewall-cmd --permanent --add-port=6443/tcp
        firewall-cmd --permanent --add-port=2379-2380/tcp
        firewall-cmd --permanent --add-port=10250/tcp
        firewall-cmd --permanent --add-port=10251/tcp
        firewall-cmd --permanent --add-port=10252/tcp
        firewall-cmd --permanent --add-port=10255/tcp
        firewall-cmd --reload
        modprobe br_netfilter
        echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

    - name: Restart master server
      reboot:
        reboot_timeout: 3600

    - name: Check connectivity
      ping:

    - name: Check docker is running
      shell: systemctl status docker | head -n 3 | tail -n 1 | awk '{ print $2 $3 }'
      register: docker_status

    - debug:
       msg:  "{{ docker_status.stdout }}"

    - name: Kubernetes cluster Initialization
      shell: kubeadm init \-\-pod-network-cidr="{{network_cid}}"  \-\-apiserver-advertise-address="{{api_advertise_address}}"
      register: kube_init_output
      #shell:
       #cmd: kubeadm init --pod-network-cidr={{network_cid}}  --apiserver-advertise-address {{api_advertise_address}}
      tags:
        - kube_init

    - name: Store Kubernetes initialization log in file /kube_init.log
      copy:
        content: "{{ kube_init_output }}"
        dest: /kube_init.log
      tags:
        - kube_init

    - name: Copying  Kubernetes configuration files
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
      tags:
        - kube_init

    - name: Deploy flanner network
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      tags:
        - kube_init

    - name: Chcecking kubernetes cluster info
      shell: kubectl get nodes -o wide
      register: kube_status
      tags:
        - kube_init

    - name: Display kubernetes cluster overview
      debug:
        msg: " {{ kube_status.stdout_lines }}"
      tags:
        - kube_init