---
- hosts: master
  vars_files:
    - env_variables

  tasks:
    - name: Add Docker apt-key to repository
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

    - name: Add Kubernetes apt-key to repository on Ubuntu
        apt_key:
          url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
          state: present

    - name: Add Docker repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present

    - name: Add Kubernetes repository
        apt_repository:
          repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
          state: present
          filename: 'kubernetes'

    - name: Install containerd.io (package that manages container lifecycle)
      shell: dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm

    - name: Install required packages
      apt:
       name: "{{ ubuntu_packages }}"
       state: latest
       update_cache: yes
       status: restarted
       enabled: yes

    - name: Install system updates
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Set firewall rules
      shell: |
        firewall-cmd --permanent --add-port=6443/tcp
        firewall-cmd --permanent --add-port=2379-2380/tcp
        firewall-cmd --permanent --add-port=10250/tcp
        firewall-cmd --permanent --add-port=10251/tcp
        firewall-cmd --permanent --add-port=10252/tcp
        firewall-cmd --permanent --add-port=10255/tcp
        firewall-cmd --reload
        modprobe br_netfilter
        echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables