---
- hosts: master
  gather_facts: yes

  tasks:
    - name: Chceck kubernetes cluster info
      shell: kubectl get nodes -o wide
      register: kube_status
      tags:
        - kube_status

    - name: Display kubernetes cluster overview
      debug:
        msg: " {{ kube_status.stdout_lines }}"
      tags:
        - kube_status