---
- hosts: master
  vars_files:
    - ../env_variables
  tasks:

    - name: Kubernetes cluster Initialization
      shell: kubeadm init \-\-pod-network-cidr="{{network_cid}}"  \-\-apiserver-advertise-address="{{api_advertise_address}}"
      register: kube_init_output
      tags:
        - kube_init

    - name: Store Kubernetes initialization log in file /kube_init.log
      copy:
        content: "{{ kube_init_output.stdout }}"
        dest: /{{ kube_init_log }}
      tags:
        - kube_init

    - name: Copy  Kubernetes configuration files
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
      tags:
        - kube_init

    - name: Deploy flanner network
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      tags:
        - kube_init

    - name: Fetch file with joining token
      fetch:
        src: /{{ kube_init_log }}
        dest: /{{ kube_init_log }}
      tags:
        - worker_join

