---
- hosts: all
  tasks:
  - name: Disable Swap on all nodes
    shell: swapoff -a

  - name: Comment Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'