---
- hosts: workers

    - name: Retreiving joining token
      shell: cat "{{ kube_init_log }}" | tail -n 2
      register: kube_join_token
      tags:
        - worker_join

    - name: Join node to cluster
      shell: "{{ kube_join_token }}"
      tags:
        - worker_join