---
- hosts: workers
  gather_facts: yes
  vars_files:
    - ../env_variables

  tasks:

    - name: Transfer file with joining token to workers
      copy:
        src: /{{ kube_init_log }}
        dest: /
        backup: yes
        force: yes
      tags:
        - worker_join

    - name: Retreive joining token
      shell: cat /{{ kube_init_log }}/ | tail -n 2
      register: kube_join_token
      tags:
        - worker_join
        -
    - name: Display joining token
      debug:
        msg: "{{ kube_join_token.stdout }}"
      tags:
        - worker_join

    - name: Join worker nodes to cluster
      shell: "{{ kube_join_token.stdout }}"
      tags:
        - worker_join