---
- hosts: workers
  gather_facts: yes
  vars_files:
    - ../env_variables

  tasks:
    - name: Display joining token
      debug:
        msg: "{{ joining_token_fact }}"
      tags:
        - worker_join

    - name: Join worker nodes to cluster
      shell: "{{ joining_token_fact }}"
      tags:
        - worker_join